### ISSUE TITLE
[HELP] Doesn't size to text

### ISSUE THREAD

**Issue by SoftCircuits** [palcarazm/bootstrap5-toggle#123]
**Describe the problem**

My toggle labels are long than normal ("North to South" and "South to North"). And unfortunately, the labels word wrap: The control does not size itself wide enough for the text, and it sizes twice as high so that it can word wrap on secod line.

![image](https://user-images.githubusercontent.com/3191331/229672275-a2695c72-933f-425c-bf00-719967d267cc.png)

Even if I force it wider, it's still too tall.

![image](https://user-images.githubusercontent.com/3191331/229671739-f884e5a0-efce-4902-a109-99e58b433f03.png)

I realize I can specify an exact width and height. But then it might not match the size of the text on some devices. The documentation says it calculates the size of the control. Is there any way to instruct the control to calculate it to put the text on a single line?

**Comment by palcarazm** [comment]
Hi @SoftCircuits, 

Your issue is quite strange, can you provide a minimal reproduction code or a codepen (https://codepen.io/pen/)? 

Thanks 😊

**Comment by SoftCircuits** [comment]
@palcarazm Looks like the issue was easy to duplicate on CodePen.

https://codepen.io/softcircuits/pen/NWOKQKv

Thanks

**Comment by palcarazm** [comment]
Thanks! I will debug and give you and answer as soon as possible.

**Comment by palcarazm** [comment]
Hi @SoftCircuits,
I have deployed the [v5.0.6](https://github.com/palcarazm/bootstrap5-toggle/releases/tag/v5.0.6) that will solve the issue.

**Comment by SoftCircuits** [comment]
@palcarazm Thanks. Looks good.
