### ISSUE TITLE
Improper cloned Bootstrap5-toggle element has wrong size

### ISSUE THREAD

**Issue by SoftCircuits** [palcarazm/bootstrap5-toggle#131]
Some time ago, I reported [this issue](https://github.com/palcarazm/bootstrap5-toggle/issues/66) where the control didn't size correctly. You were kind enough to do update v5.0.6, which fixed that issue. However, that change may have broken some other code we had.

Our other code clones a bootstrap5-toggle element. This was working fine. But now, the cloned element does not have the correct height.

I have created a [CodePen](https://codepen.io/softcircuits/pen/LYgOjQz) that specifically demonstrates the issue.

If you could assist with a fix or workaround, I would greatly appreciate it.

**Comment by palcarazm** [comment]
Hi, I will take a look ASAP.

**Comment by SoftCircuits** [comment]
@palcarazm Hello, just a friendly follow up. Have you had any chance to take a look at this issue yet? Thanks.

**Comment by palcarazm** [comment]
Hi @SoftCircuits 

I didn't find the root cause. I will keep debugging this weekend

**Comment by palcarazm** [comment]
Hi @SoftCircuits,

I found the issue. 

If the clone is not added to the html the min height is set to 0px. Just inverse tne append of the clone and render of the toggle.

[Here a fork of your codepen with the fix](https://codepen.io/palcarazm/pen/mdzLxBo)

And a minimal reproduction code (in case someone else need it)
```html
<main class="container bg-white px-3 py-3 rounded">
    <p>
        Click the button to clone the toggle control container.
    </p>

    <div id="source" class="row">
        <div class="col-md-3">
            <div class="mb-3 source-type">
                <input id="toggle-control" type="checkbox" class="form-control" data-toggle="toggle"
                    data-offlabel="Railcar" data-onlabel="Storage" data-offstyle="success" data-onstyle="danger"
                    data-width="100%" checked="@(isStorage ? " checked" : null)">
            </div>
        </div>
    </div>

    <div id="target"></div>

    <button class="btn btn-outline-secondary" id="clone">Clone</button>
</main>
```
```javascript
$("#clone").on("click", function () {
  var $source = $("#source");
  // Clear bootstrap toggle before cloning
  var $ctl = $source.find("input");
  $ctl.bootstrapToggle("destroy");
  // Clone source
  var $clone = $source.clone(true, true);
  // Restore original control
  $ctl.bootstrapToggle();
  // Append clone
  $("#target").append($clone);
  // Enable bootstrap toggle for clone
  $ctl = $("#target").find("input");
  $ctl.bootstrapToggle();
});
```
