### ISSUE TITLE
Toggle Swith does not work if you put it inside a <fieldset>

### ISSUE THREAD

**Issue by aabouganem** [palcarazm/bootstrap5-toggle#132]
example:

<fieldset>
<div class="col-auto">
	<label for="cola_c32">Var. de Interfaz:&nbsp;</label>
	<a>
		<i class="fas fa-info-circle info"  data-toggle="tooltip" data-placement="top" ></i>
	</a>
	<input type="checkbox" name="colac32" id="colac32" data-toggle="toggle" data-size="sm" data-onstyle="primary" data-on="Si" data-off="No" <?php if($row['setinterfacevar'] == "yes"){?> checked="checked" <?php } ?> disabled>
</div>

output must be a complete switch but it is not
 the switch is displayed as:
![imagen](https://user-images.githubusercontent.com/132527291/236083427-082c6b44-e142-471f-bdbf-1b3188de00c8.png)

**Comment by palcarazm** [comment]
Hi @aabouganem,

Can you provided a minimal reproduction code or even a codepen ([here a template for bs-toggle@5](https://codepen.io/palcarazm/pen/mdGVGqB)).

Thanks!

**Comment by palcarazm** [comment]
Hi @aabouganem,

I can't reproduce your issue
