### ISSUE TITLE
Is it usable to angular 13

### ISSUE THREAD

**Issue by mojidul31** [palcarazm/bootstrap5-toggle#148]
Is it usable to angular 13? I am trying to use it my angular 13 project but not working. can you help me?

**Comment by palcarazm** [comment]
Hi, 

The plugin is vanilla JavaScript so it will not work with the dom dynamic render of angular or react. You should destroy the google instance and construct the toggle instance with the js api each time the component is dismounted and mounted

**Comment by palcarazm** [comment]
Refers #128
