### ISSUE TITLE
[BUG] Preview Page does not render toggles

### ISSUE THREAD

**Issue by aschoerg** [palcarazm/bootstrap5-toggle#154]
**Describe the bug**
[Docs page](https://palcarazm.github.io/bootstrap5-toggle/) does not render toggles.

**To Reproduce**
1. Visit https://palcarazm.github.io/bootstrap5-toggle/
2. Scroll down to examples

**Screenshots**
![image](https://github.com/palcarazm/bootstrap5-toggle/assets/6042536/ecda79e7-99fd-4b62-bd75-1a898b229d46)

**Desktop:**
 - OS: Win
 - Browser: Chrome
 - Version: 120

**Comment by palcarazm** [comment]
Hi, 

Thanks for reporting the issue. The demo page is rendered by loading async files for each section. 

This is not a good practice, but is a simple solution for having a demo static page.

Sometimes the render effect is launch when some sections are still loading, causing this bug.
