### ISSUE TITLE
[BUG] [Violation]Added non-passive event listener to a scroll-blocking event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by g-pane** [palcarazm/bootstrap5-toggle#156]
**Describe the bug**
[Violation]Added non-passive event listener to a scroll-blocking event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**To Reproduce**
Steps to reproduce the behavior and minimal code:
1. Go to 'Console' on Chrome/Edge

**Expected behavior**
No console warning

**Package:**
 - Bootstrap 5 Toggle ECMAS version

**Desktop:**
(please complete the following information)
 - OS: Windows 10
 - Browser: Edge/Chrome

**Additional context**
It happened with defferent event like "touchstart" and more.

**Comment by palcarazm** [comment]
Forgive me for attending to the matter belatedly. I have been busy with other projects.

I can see that this is a complex issue that needs to be looked at with caution. I am leaving the ticket open in case someone could assist me with the solution.

It should occur in the block ["// 9: Add listeners"](https://github.com/palcarazm/bootstrap5-toggle/blob/7fff2692dee1cafc1d59631e532c6a1afe8703e6/js/bootstrap5-toggle.ecmas.js#L296 )

Thanks for your report 😄 .
