### ISSUE TITLE
[BUG] 5.1.0 doesn't render HTML

### ISSUE THREAD

**Issue by BudsieBuds** [palcarazm/bootstrap5-toggle#174]
**Describe the bug**
After updating from `5.0.6` to `5.1.0`, HTML isn't rendered inside the toggle.

**To Reproduce**
```html
<input type="checkbox" checked data-toggle="toggle" data-onlabel="<i class='bi-play'></i> Play" data-offlabel="<i class='bi-pause'></i> Pause">
```

**Screenshots**
Bootstrap 5 Toggle `5.0.6`:

![Bootstrap 5 Toggle 5.0.6](https://github.com/palcarazm/bootstrap5-toggle/assets/12870258/18cd144b-2b6a-4c99-b917-aacb66ff2ccf)

Bootstrap 5 Toggle `5.1.0`:

![Bootstrap 5 Toggle 5.1.0](https://github.com/palcarazm/bootstrap5-toggle/assets/12870258/53bb8c2e-dc0d-4567-8146-b7413ee7a719)

**Package:**
 - Bootstrap 5 Toggle version: `5.1.0`
 - Bootstrap version: `5.3.3`

**Desktop:**
 - Browser: Firefox

**Comment by palcarazm** [comment]
Thanks for reporting.

The issue is fixed in [v5.1.1](https://github.com/palcarazm/bootstrap5-toggle/releases/tag/v5.1.1).

The issue is a border effect of #160
