### ISSUE TITLE
[BUG]- It is not working even after I reference the CDN in my project

### ISSUE THREAD

**Issue by Banda943224** [palcarazm/bootstrap5-toggle#178]
Hello Team,

I have added below CDN to my project but still toggle button is not working as expected. 

Please can you help?

<link href="https://cdn.jsdelivr.net/npm/bootstrap5-toggle@5.1.1/css/bootstrap5-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap5-toggle@5.1.1/js/bootstrap5-toggle.jquery.min.js"></script>

**Comment by palcarazm** [comment]
Hi can you provide screenshots and code to reproduce the error?
