### ISSUE TITLE
[BUG] Render on input group

### ISSUE THREAD

**Issue by palcarazm** [palcarazm/bootstrap5-toggle#24]
**Describe the bug**
If you set the component in an input-group the render is not correct.

**To Reproduce**
```html
<main class="container">
  <div class="input-group input-group-sm mb-3">
    <span class="input-group-text" id="inputGroup-sizing-sm">Small</span>
    <input type="checkbox" checked data-toggle="toggle" data-size="sm">
  </div>
  <div class="input-group mb-3">
    <span class="input-group-text" id="inputGroup-sizing-default">Default</span>
    <input type="checkbox" checked data-toggle="toggle">
  </div>
  <div class="input-group input-group-lg">
    <span class="input-group-text" id="inputGroup-sizing-lg">Large</span>
    <input type="checkbox" checked data-toggle="toggle" data-size="lg">
  </div>
</main>
<script>$('input[data-toggle="toggle"]').bootstrapToggle();</script>
```

**Expected behavior**
Render correctly

**Screenshots**
|On|Off|
|---|---|
|![image](https://user-images.githubusercontent.com/79061172/177764371-75afa54b-97f8-4d02-9acd-5b2059e4ece4.png)|![image](https://user-images.githubusercontent.com/79061172/177764434-5ed206b4-a344-4a55-9962-2b11a19ea09b.png)|

**Package (please complete the following information):**
 - Bootstrap 5 Toggle version: 4.1.0
 - Bootstrap version: 5.1.3

**Desktop (please complete the following information):**
 - OS: Win
 - Browser: Chrome

**Comment by palcarazm** [comment]
refers: gitbrent/bootstrap4-toggle#32
by: @daniel-scatigno
fixed base in : @bryan-brancotte [comment](https://github.com/gitbrent/bootstrap4-toggle/issues/32#issuecomment-616974580)

**Comment by palcarazm** [comment]
hi @daniel-scatigno,

Do you want to fixed sending a pull-request for been corretly acknowledge?

Just in bootstrap 5 there is not needed to add the class `input-group-btn`, so the fix will be:

```css
.input-group .toggle-on,
.input-group .toggle-off{
    position: absolute;
}
```

**Comment by bryan-brancotte** [comment]
Hi @palcarazm 

Thanks for the proposition, you can push the fix by yourself if you are ok with this.
