### ISSUE TITLE
[FEATURE] Tristate toggle

### ISSUE THREAD

**Issue by palcarazm** [palcarazm/bootstrap5-toggle#40]
**Is your feature request related to a problem? Please describe.**
Normal checkboxes  support an indeterminate state via JavaScript.
![image](https://user-images.githubusercontent.com/79061172/179391251-cfb70d4b-9a1b-4d86-88a0-8d642d65fda0.png)

**Describe the solution you'd like**
- Add support to indeterminate state.
- Add styling to indeterminated toggle elements to show when they're indeterminated .

**Describe alternatives you've considered**
😞 

**Additional context**
Original from:
- https://github.com/minhur/bootstrap-toggle/issues/66 by @paulomcnally
- https://github.com/minhur/bootstrap-toggle/issues/175 by @loginetsolutions
- https://github.com/minhur/bootstrap-toggle/issues/202 by @solsticedhiver
- https://github.com/minhur/bootstrap-toggle/issues/212 by @JaiKumaresh
- https://github.com/gitbrent/bootstrap4-toggle/issues/38 by @Mina-R-Meshriky 

:ballot_box_with_check: **Task list**
- [x] Develop feature/fix jQuery
- [x] Develop feature/fix ECMAS 
- [x] Add cypress test coverage
- [ ] Update docs (is needed)

**Comment by johnwc** [comment]
@palcarazm was this feature added? I do not see any examples

**Comment by palcarazm** [comment]
Hi

```
<input type="checkbox" checked data-toggle="toggle" tristate>
```

**Comment by johnwc** [comment]
Is this still the demo site for this?
https://www.bootstraptoggle.com/

**Comment by palcarazm** [comment]
No, the demo page is https://palcarazm.github.io/bootstrap5-toggle/

The website you refer is for bootstrap 4 who has not support

**Comment by saper-2** [comment]
I think there is a small bug, when checkbox is in `indeterminate` state (the "3rd state"), and then the toggle is created the `indeterminate` state is not applied to toggle.

here is my test: https://codepen.io/sapers-2/pen/XJKbZaQ
