### ISSUE TITLE
CDNs are missing ecmas files

### ISSUE THREAD

**Issue by MeikelLP** [palcarazm/bootstrap5-toggle#44]
**Describe the bug**
https://unpkg.com/browse/bootstrap5-toggle@4.2.0/js/ is missing ecmas files while 4.2 jQuery files are present. AFAIK UNPKG uses the NPM package as source.
https://www.jsdelivr.com/package/npm/bootstrap5-toggle?path=js as well

**Expected behavior**
jQuery-less should be available on UNPKG as well

**Package (please complete the following information):**
 - Bootstrap 5 Toggle version: 4.2

**Comment by palcarazm** [comment]
Hi @MeikelLP,

The ecmas files (#2) will be available from version [4.3.0](https://github.com/palcarazm/bootstrap5-toggle/milestone/1) scheduled for release on the 31st. However, if you need it urgently, I can remove the toggle tristate (#40) from this version and release [4.3.0](https://github.com/palcarazm/bootstrap5-toggle/milestone/1) between today and tomorrow.

**Comment by MeikelLP** [comment]
Hi @palcarazm

Thank you for this quick response. It is not urgent. I didn't know it was planned for 4.3. Felt like it was missing :)
