### ISSUE TITLE
Support for Bootstrap 5.2.0

### ISSUE THREAD

**Issue by palcarazm** [palcarazm/bootstrap5-toggle#45]
Perform a non regression  test and analyse.

**Comment by palcarazm** [comment]
Hi @Jackietkfrost , 

Thanks for your comment.

I think a separated issue will be great!

Can you precise if the icon is from a dependency (bootstrap-icon / fontsawesome...) or just an image? 

Thank you very much 😊!

**Comment by Jackietkfrost** [comment]
It's a Bootstrap-Icon svg that was downloaded and it's being used locally! I'll go ahead and open a ticket.

**Comment by palcarazm** [comment]
Tests done. 

Detected Issues:
- #51
