### ISSUE TITLE
[BUG] 'Empty string passed to getElementById().' warning on Firefox.

### ISSUE THREAD

**Issue by DarkNami** [palcarazm/bootstrap5-toggle#80]
**Describe the bug**
If the `<input>` has not set `ID` attribute, it will cause 'Empty string passed to getElementById().' warning on Firefox.

**To Reproduce**
Steps to reproduce the behavior and minimal code:
1. Launch Firefox
2. Open URL https://palcarazm.github.io/bootstrap5-toggle/
3. Press F12 open developer panel.
4. Click 'Console' panel.
5. Hover cursor to any bootstrap toggle.
6. You will see many 'Empty string passed to getElementById().' warnings.

**Expected behavior**
Don't add `for` attribute if attribute `ID` does not exist.

**Screenshots**
![Issue](https://user-images.githubusercontent.com/5100919/207577584-1ee87f8b-142e-43b7-ad5f-912db0040383.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 108

**Additional context**
I had fix this issue for old bootstrap4-toggle on my fork.
https://github.com/DarkNami/bootstrap4-toggle/commit/76fb0c1d985db32a42a81c829238765b335d24ec

Do you need I create a PR for this issue or palcarazm can fix it ? (it is short, only 4 lines changes.)

**Comment by palcarazm** [comment]
Hi @DarkNami , 

Thanks for the issue 😊.

If you can do a PR so you will be listed as controntibutor.
If you cann't I will read and import your code an add the source in comments.

**Comment by DarkNami** [comment]
Hi @palcarazm ,

I am not familiar with GitHub. :dizzy_face:

I have tried to fork your repositorie `palcarazm / bootstrap5-toggle`, but GitHub say 'No more forks can be created. These forks already exist.'. I don't know how to sync my `bootstrap4-toggle` fork to your `bootstrap5-toggle`. :thinking:

**Comment by palcarazm** [comment]
Okay, don't worry. I will merge your changes and put you as co-author of the commit.

**Comment by DarkNami** [comment]
Thank you. :thumbsup:

**Comment by palcarazm** [comment]
Done! It will be released in the next patch.

**Comment by DarkNami** [comment]
I have tested it, warning is stopped.
Thank you.
